# Generated by Django 5.1.2 on 2024-10-30 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0002_review'),
        ('patient', '0001_initial'),
        ('vaccine', '0002_alter_vaccine_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_number', models.CharField(choices=[('1', 'First Dose'), ('2', 'Second Dose'), ('3', 'Third Dose'), ('4', 'fourth Dose'), ('5', 'fifth Dose')], max_length=10)),
                ('appointment_date_time', models.DateTimeField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.vaccine')),
            ],
        ),
    ]
