# Generated by Django 5.1.2 on 2024-10-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='manufacturer',
            field=models.CharField(max_length=250),
        ),
    ]
